{{ if .Values.runtime.deploy }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway-runtime
  labels:
    app: api-gateway-runtime
spec:
  replicas: {{ .Values.runtime.replicaCount }}
  template:
    metadata:
      labels:
        app: api-gateway-runtime
    spec:
      containers:
        - name: api-gateway-runtime
          image: "{{ .Values.runtime.image.repository }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          ports:
          - containerPort: 8080
          env:
          - name: CONSOLE_HOST
            value: "{{ .Values.runtime.env.CONSOLE_HOST }}"
          - name: registry.zone
            value: "{{ .Values.runtime.env.registry_zone }}"
          - name: registry.group
            value: "{{ .Values.runtime.env.registry_group }}"
          - name: CONSOLE_PORT
            value: "{{ .Values.runtime.env.CONSOLE_PORT }}"
          - name: REDIS_HOST
            {{ if .Values.redis.deploy }}
            value: "api-gateway-redis"
            {{ else }}
            value: "{{ .Values.redis.host }}"
            {{ end }}
          - name: REDIS_PORT
            {{ if .Values.redis.deploy }}
            value: "6379"
            {{ else }}
            value: "{{ .Values.redis.port }}"
            {{ end }}
          - name: SSO_ENDPOINT
            value: "{{ .Values.runtime.env.SSO_ENDPOINT }}"
{{ end }}