{{ if .Values.runtime.deploy }}
{{ if .Values.runtime.ingress.enabled }}
{{ range .Values.runtime.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-ingress"
  labels:
    app: {{ template "fullname" $ }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: api-gateway-console
            servicePort: 8080
---
{{ end }}
{{ end }}
{{ end }}