{{ if .Values.runtime.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-runtime
  labels:
    app: api-gateway-runtime
spec:
  type: {{ .Values.runtime.service.type }}
  ports:
    - port: 8080
      {{- if (and (eq .Values.console.service.type "NodePort") (not (empty .Values.console.service.port)))}}
      nodePort: {{ .Values.console.service.port }}
      {{- end }}
      name: http
  selector:
    app: api-gateway-runtime
{{ end }}