apiVersion: v1
kind: Service
metadata:
  name: api-gateway-runtime
  labels:
    app: api-gateway-runtime
spec:
  type: {{ .Values.runtime.service.type }}
  ports:
    - port: 8080
      nodePort: {{ .Values.runtime.service.port }}
      name: http
  selector:
    app: api-gateway-runtime
