apiVersion: v1
kind: Service
metadata:
  name: api-gateway-runtime
  labels:
    app: api-gateway-runtime
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: api-gateway-runtime
