apiVersion: v1
kind: Service
metadata:
  name: api-gateway-console
  labels:
    app: api-gateway-console
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - port: 8080
      {{- if (and (eq .Values.console.service.type "NodePort") (not (empty .Values.console.service.port)))}}
      nodePort: {{ .Values.console.service.port }}
      {{- end }}
      name: http
  selector:
    app: api-gateway-console
