## Console ##
console:

  deploy: true

  image:
    repository: hub.bingosoft.net/bingoapigw/api-gateway-console:latest

  service:
    type: NodePort
    port: 

  ingress:
    enabled: true
    hosts:
    - name: gateway.console.local

  env:
    db_url: jdbc:mysql://172.16.1.8:3336/paas_apigw?characterEncoding=utf-8&useSSL=false
    db_username: paas
    db_password: Bingo@devops1117

    user_db_url: jdbc:mysql://172.16.1.8:3336/paas_user?characterEncoding=utf-8&useSSL=false
    user_db_username: paas
    user_db_password: Bingo@devops1117

    oauth2_serverUrl: http://114.67.33.121:8081/sso

## Runtime ##
runtime:

  deploy: true

  image:
    repository: hub.bingosoft.net/bingoapigw/api-gateway-runtime:latest
  
  service:
    type: NodePort
    port: 

  ingress:
    enabled: true
    hosts:
    - name: gateway.runtime.local

  env:
    SSO_ENDPOINT: http://172.16.1.9:8081/sso
    registry_zone: default
    registry_group: console

## Redis ##
redis:

  deploy: true

  host: 

  port: 6379