appVersion: 1.0.0
version: 1.0.0
description: 开放源码，高级键值存储。它通常被称为数据结构服务器，因为钥匙可以包含字符串、散列、列表、集合和排序集。
engine: gotpl
home: http://redis.io/
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: redis
sources:
- https://github.com/bitnami/bitnami-docker-redis